"""Build NeMo/chat JSONL for DFlash2 training from Ornith self-distillation dumps.

NeMo wants OpenAI-format {"messages": [...]} rows with assistant text regenerated by
the teacher. That is drafter/data/gen.jsonl (prompt_ids + output_ids from gen_data.py).

  python drafter/convert_gen_to_chat.py
  python drafter/convert_gen_to_chat.py --src drafter/data/gen.jsonl --dst drafter/data/chat.jsonl
  python drafter/convert_gen_to_chat.py --smoke-only

Pins mask_token_id=248077 (see dflash2_const.py). Writes chat_smoke.jsonl always.
"""
from __future__ import annotations

import json, os, sys, argparse
HERE = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from dflash2_const import MASK_TOKEN_ID, PAD_TOKEN_ID, EOS_TOKEN_ID, VOCAB_SIZE, assert_mask_unused

parser = argparse.ArgumentParser()
parser.add_argument("--model", default=os.path.join(REPO, "models", "Ornith-1.5-9B-MixedInt4-AutoRound"))
parser.add_argument("--src", default=os.path.join(HERE, "data", "gen.jsonl"))
parser.add_argument("--prompts", default=os.path.join(HERE, "data", "prompts.jsonl"))
parser.add_argument("--dst", default=os.path.join(HERE, "data", "chat.jsonl"))
parser.add_argument("--smoke-only", action="store_true")
parser.add_argument("--min-output", type=int, default=8)
args = parser.parse_args()
os.makedirs(os.path.dirname(args.dst), exist_ok=True)
assert_mask_unused(args.model)


def decode_ids(ids, model_dir):
    try:
        from transformers import AutoTokenizer
        tok = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
        return tok.decode(ids, skip_special_tokens=False)
    except Exception:
        pass
    try:
        from tokenizers import Tokenizer
        t = Tokenizer.from_file(os.path.join(model_dir, "tokenizer.json"))
        return t.decode(ids)
    except Exception:
        pass
    vocab = json.load(open(os.path.join(model_dir, "tokenizer.json")))
    id2 = {}
    for tok, i in (vocab.get("model") or {}).get("vocab", {}).items():
        id2[int(i)] = tok
    for t in vocab.get("added_tokens") or []:
        id2[int(t["id"])] = t.get("content", "")
    return "".join(id2.get(int(i), "") for i in ids)


def strip_special(text):
    for s in ("<|im_start|>", "<|im_end|>", "<|endoftext|>"):
        text = text.replace(s, "")
    return text.strip()


SMOKE = [
    {"messages": [
        {"role": "user", "content": "Write a Python function that returns the n-th Fibonacci number."},
        {"role": "assistant", "content": "```python\ndef fib(n: int) -> int:\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n```"},
    ]},
    {"messages": [
        {"role": "user", "content": "Explique em português o que é um Dockerfile."},
        {"role": "assistant", "content": "Um Dockerfile é um arquivo de texto com instruções para construir uma imagem Docker: FROM, RUN, COPY, CMD."},
    ]},
    {"messages": [
        {"role": "user", "content": "List the steps to run a vLLM OpenAI server on port 18020."},
        {"role": "assistant", "content": "Install vLLM, point it at the model directory, then `vllm serve MODEL --port 18020 --host 0.0.0.0`."},
    ]},
    {"messages": [
        {"role": "user", "content": "What is speculative decoding?"},
        {"role": "assistant", "content": "A small drafter proposes several tokens; the target verifies them in one forward pass. Rejected tokens truncate the proposal. The sampled distribution matches the target."},
    ]},
]

smoke_path = os.path.join(HERE, "data", "chat_smoke.jsonl")
with open(smoke_path, "w") as f:
    for row in SMOKE:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")
print(f"wrote {smoke_path} ({len(SMOKE)} rows)  mask_token_id={MASK_TOKEN_ID} "
      f"(pad={PAD_TOKEN_ID} eos={EOS_TOKEN_ID} vocab={VOCAB_SIZE})")

if args.smoke_only:
    sys.exit(0)

if not os.path.isfile(args.src):
    print(f"no {args.src}; generate it with drafter/collect_prompts.py then drafter/gen_data.py")
    print(f"smoke data is ready at {smoke_path}")
    sys.exit(0)

n_in = n_out = 0
with open(args.dst, "w") as out, open(args.src) as src:
    for line in src:
        line = line.strip()
        if not line:
            continue
        rec = json.loads(line)
        n_in += 1
        out_ids = rec.get("output_ids") or []
        if len(out_ids) < args.min_output:
            continue
        prompt_ids = rec.get("prompt_ids") or []
        # Prefer original chat turns when we still have the prompt file id.
        user = None
        # Decode assistant from generated tokens only.
        assistant = strip_special(decode_ids(out_ids, args.model))
        if not assistant:
            continue
        # Reconstruct a single-turn chat: decode the prompt and take the last user span
        # if the original messages are not attached.
        msgs = rec.get("messages")
        if not msgs:
            prompt_text = strip_special(decode_ids(prompt_ids, args.model))
            user = prompt_text
            # Chat templates wrap the user turn; keep the decoded prompt as the user content
            # when we cannot recover structured messages. Better than dropping the row.
            msgs = [{"role": "user", "content": user or prompt_text},
                    {"role": "assistant", "content": assistant}]
        else:
            msgs = [m for m in msgs if m.get("role") in ("system", "user", "assistant")]
            # Replace / append the assistant turn with the regenerated text.
            if msgs and msgs[-1].get("role") == "assistant":
                msgs[-1] = {"role": "assistant", "content": assistant}
            else:
                msgs = list(msgs) + [{"role": "assistant", "content": assistant}]
        if not any(m.get("role") == "user" for m in msgs):
            continue
        if not any(m.get("role") == "assistant" for m in msgs):
            continue
        out.write(json.dumps({"id": rec.get("id"), "src": rec.get("src"),
                              "think": rec.get("think"), "messages": msgs},
                             ensure_ascii=False) + "\n")
        n_out += 1

print(f"converted {n_in} gen rows -> {n_out} chat rows at {args.dst}")
print(f"mask_token_id={MASK_TOKEN_ID}  (do not use 248070/<|audio_start|>)")
